### ISSUE TITLE
tool-avrdude not installing

### ISSUE THREAD

**Issue by novemberalpha** [OpenAgInitiative/openag_brain_docker_rpi#27]
Hey gang,

I'm trying to rebuild new docker instances and after a git pull and complete docker image rebuild I'm getting the following error when I try to flash the Arduino.

```
pi@adcc1d370aed:~$ rosrun openag_brain flash
Initializing PlatformIO project
OpenAg firmware project initialized!
Warning: no modules specified for the project
Downloading "rosserial_arduino_libs"
Cloning into '/tmp/tmpy6j4Uo/lib/rosserial_arduino_libs'...
remote: Counting objects: 313, done.        
remote: Total 313 (delta 0), reused 0 (delta 0), pack-reused 313        
Receiving objects: 100% (313/313), 134.99 KiB | 0 bytes/s, done.
Resolving deltas: 100% (198/198), done.
Checking connectivity... done.
[Sun Apr 23 03:05:00 2017] Processing megaatmega2560 (platform: atmelavr, board: megaatmega2560, framework: arduino)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Installing framework-arduinoavr package:
Downloading  [####################################]  100%          
Unpacking  [####################################]  100%          
Installing tool-avrdude package:
Downloading  [####################################]  100%          
Error: The 'sha1' sum '1c4eab065c4aafb594737d619df02c907e57286e' of downloaded file 'tool-avrdude-linux_armv6l-1.60001.1.tar.gz' is not equal to remote '1a5349907a5ebc7f12b8205d714855e3e810cd47'
Error: Compilation failed
Done
```
Are you seeing this on your end? I've done this a hundred times and I'm pretty sure I'm doing it correctly. What could be going wrong? 

Thanks! 

J

**Comment by novemberalpha** [comment]
I ran apt-get update / upgrade and while a ton of files were updated, there was no improvement on the situation documented above. == still broke.

**Comment by sp4ghet** [comment]
It appears to run when you do `pio upgrade`
http://forum.openag.media.mit.edu/t/rosserial-tool-avrdude-build-failing-with-not-matching-sha/1774/3

@LeonChambers is there a reason for the plaformio version being 2.11? or can it be updated with no problem.

**Comment by LeonChambers** [comment]
There were breaking changes in platformio 3.0 that would break the Arduino build system. From what I remember, it shouldn't be too much work to update the codebase to work with platformio 3.0, but I never got around to actually doing it.

**Comment by sp4ghet** [comment]
Would the changes be to each firmware module, or to something in openag_python/brain? Either way I'm thinking it would make sense to upgrade to platformio 3. Thanks for the input!

**Comment by LeonChambers** [comment]
It would be in openag_python/brain.

**Comment by sp4ghet** [comment]
I just tried it out, there's not much broken on openag_python/brain, but jake broke a firmware module last month that fails under 3.0 and probably gives warnings or something on 2.

We've successfully compiled and written to an arduino so it looks good!
